name: Java CI

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Install xmlstarlet
      run: sudo apt-get install -y xmlstarlet

    - name: Build with Gradle
      run: |
        bash ./gradlew build
        bash ./gradlew publishToMavenLocal

    - name: List build directory for debugging
      run: ls -R ~/.m2

    - name: Extract version from generated POM file
      id: extract_version
      run: |
        xml_file=$(find ~/.m2/repository/org/tdf/ -type f -name "*.pom" -print -quit)
        VERSION=$(xmlstarlet sel -N xmlns="http://maven.apache.org/POM/4.0.0" -t -v "//xmlns:project/xmlns:version" "$xml_file")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Checkout artifact repo
      uses: actions/checkout@v4
      with:
        repository: 'RiV-chain/artifact'

    - name: Create package directories
      run: |
        mkdir -p artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}

    - name: Copy JAR, POM, SHA-1, and MD5 files
      run: |
        cp -r ~/.m2/repository/org artifact
        mv artifact/org/tdf/${{ github.event.repository.name }}/maven-metadata-local.xml artifact/org/tdf/${{ github.event.repository.name }}/maven-metadata.xml
        sha1sum artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.jar > artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.jar.sha1
        md5sum artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.jar > artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.jar.md5
        sha1sum artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.pom > artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.pom.sha1
        md5sum artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.pom > artifact/org/tdf/${{ github.event.repository.name }}/${{ env.VERSION }}/${{ github.event.repository.name }}-${{ env.VERSION }}.pom.md5

    - name: Commit and push files
      run: |
        cd artifact
        git config user.name "vikulin"
        git config user.email "vadym.vikulin@rivchain.org"
        git remote add gh-token "https://${{ secrets.github_token}}@github.com/RiV-Chain/artifacts.git"
        git add .
        git commit -m "Add build artifacts for version ${{ env.VERSION }}"
        git push
