name: Maven artifact publish

on: 
  workflow_dispatch:

permissions:                    # Global permissions configuration starts here
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maven publish action
      uses: RiV-chain/github-publish-maven-action@main
      with:
        gh_pat: ${{ secrets.MAVEN_PAT }}
        artifact_repo: 'RiV-chain/artifact'
        gradle_file_path: './gradlew'
        java_version: '8'
